Script started on 2016年03月15日 (週二) 01時31分58秒
]0;C14026028@2015cpp: ~[01;32mC14026028@2015cpp[00m:[01;34m~[00m$ script lab1.scriptgit push origin master[12Pcommit[1Padd .[4P./labg++ -o lab lab1.cpp[7Pvim[C[C[C[C[C[C[C[C[C[7P./labg++ -o lab lab1.cpp[7Pvim[C[C[C[C[C[C[C[C[C[7P./labg++ -o lab lab1.cpp[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[Kwhoami; pwd
C14026028
/home/C14026028
]0;C14026028@2015cpp: ~[01;32mC14026028@2015cpp[00m:[01;34m~[00m$ git config -1
error: unknown switch `1'
usage: git config [options]

Config file location
    --global              use global config file
    --system              use system config file
    --local               use repository config file
    -f, --file <file>     use given config file

Action
    --get                 get value: name [value-regex]
    --get-all             get all values: key [value-regex]
    --get-regexp          get values for regexp: name-regex [value-regex]
    --replace-all         replace all matching variables: name value [value_regex]
    --add                 adds a new variable: name value
    --unset               removes a variable: name [value-regex]
    --unset-all           removes all matches: name [value-regex]
    --rename-section      rename section: old-name new-name
    --remove-section      remove a section: name
    -l, --list            list all
    -e, --edit            opens an editor
    --get-color <slot>    find the color configured: [default]
    --get-colorbool <slot>
                          find the color setting: [stdout-is-tty]

Type
    --bool                value is "true" or "false"
    --int                 value is decimal number
    --bool-or-int         value is --bool or --int
    --path                value is a path (file or directory name)

Other
    -z, --null            terminate values with NUL byte

]0;C14026028@2015cpp: ~[01;32mC14026028@2015cpp[00m:[01;34m~[00m$ git clone https://github.com/wan0124/lab1.git
fatal: destination path 'lab1' already exists and is not an empty directory.
]0;C14026028@2015cpp: ~[01;32mC14026028@2015cpp[00m:[01;34m~[00m$ exit

Script done on 2016年03月15日 (週二) 01時33分07秒
